# Generated by Django 4.1.5 on 2023-01-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0002_rename_test_data_split_experiment_test_data_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationmodel',
            name='ignored_columns',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
