# Generated by Django 4.1.3 on 2022-12-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0003_remove_experiment_id_remove_traindata_colnames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='var_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
