# Generated by Django 4.1.5 on 2023-01-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0004_resultsclassificationmodel_intercept'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodel',
            name='example_field',
            field=models.TextField(default='as', max_length=20000),
            preserve_default=False,
        ),
    ]
