# Generated by Django 4.1.3 on 2022-12-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0005_traindata_train_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='train_data_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
