# Generated by Django 4.1.5 on 2023-01-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0005_classificationmodel_example_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationmodel',
            name='example_field',
        ),
    ]
