# Generated by Django 4.1.3 on 2022-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0009_rename_experiment_id_variables_experiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='train_data_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
