# Generated by Django 4.1.3 on 2022-12-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0017_experiment_do_create_data_experiment_output_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationarity',
            name='stationarity_passed',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
