# Generated by Django 4.1.3 on 2022-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0020_manualvariableselection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualvariableselection',
            name='input_columns',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
