# Generated by Django 4.1.3 on 2022-12-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0023_fibonacciexperiment_experiment_experiment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FibonacciExperiment',
            new_name='Fibonacci',
        ),
    ]
