# Generated by Django 4.1.3 on 2022-12-07 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0024_rename_fibonacciexperiment_fibonacci'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fibonacci',
            new_name='Fibonnaci',
        ),
    ]
