# Generated by Django 4.1.3 on 2022-12-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0034_experiment_run_end_time_experiment_run_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fibonnaci',
        ),
    ]
