# Generated by Django 4.1.3 on 2022-12-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0035_delete_fibonnaci'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindata',
            name='column_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traindata',
            name='no_of_cols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traindata',
            name='no_of_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
