# Generated by Django 4.1.3 on 2022-12-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0036_traindata_column_names_traindata_no_of_cols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualvariableselection',
            name='keep_columns',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
