# Generated by Django 4.1.3 on 2022-12-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0042_remove_classificationmodel_test_results_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassificationResults',
            new_name='ResultsClassificationmodel',
        ),
    ]
