# Generated by Django 4.1.3 on 2022-12-22 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic_build', '0047_alter_experiment_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('notification', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classificationmodel',
            name='results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic_build.resultsclassificationmodel'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='output_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_data', to='logistic_build.traindata'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='previous_experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic_build.experiment'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='traindata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_train_data', to='logistic_build.traindata'),
        ),
        migrations.AlterField(
            model_name='resultsclassificationmodel',
            name='test_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='logistic_build.classificationmetrics'),
        ),
        migrations.AlterField(
            model_name='resultsclassificationmodel',
            name='train_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_results', to='logistic_build.classificationmetrics'),
        ),
    ]
