# Generated by Django 4.1.3 on 2022-12-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0055_alter_experiment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('explained_variance', models.FloatField(blank=True, null=True)),
                ('experiment_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsRegressionmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficients', models.TextField(blank=True, max_length=20000, null=True)),
                ('feature_cols', models.TextField(blank=True, max_length=20000, null=True)),
                ('tValues', models.TextField(blank=True, max_length=20000, null=True)),
                ('pValues', models.TextField(blank=True, max_length=20000, null=True)),
                ('dispersion', models.FloatField(blank=True, null=True)),
                ('coefficientStandardErrors', models.TextField(blank=True, max_length=20000, null=True)),
                ('nullDeviance', models.FloatField(blank=True, null=True)),
                ('residualDegreeOfFreedomNull', models.FloatField(blank=True, null=True)),
                ('residualDegreeOfFreedom', models.FloatField(blank=True, null=True)),
                ('deviance', models.FloatField(blank=True, null=True)),
                ('AIC', models.FloatField(blank=True, null=True)),
                ('test_results', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='logistic_build.regressionmetrics')),
                ('train_results', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_results', to='logistic_build.regressionmetrics')),
            ],
        ),
        migrations.CreateModel(
            name='Regressionmodel',
            fields=[
                ('experiment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logistic_build.experiment')),
                ('label_col', models.CharField(blank=True, max_length=100, null=True)),
                ('train_split', models.FloatField(blank=True, null=True)),
                ('test_split', models.FloatField(blank=True, null=True)),
                ('feature_cols', models.TextField(blank=True, max_length=20000, null=True)),
                ('ignored_columns', models.TextField(blank=True, max_length=20000, null=True)),
                ('cross_validation', models.BooleanField(default=False)),
                ('results', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic_build.resultsregressionmodel')),
            ],
            bases=('logistic_build.experiment',),
        ),
    ]
