# Generated by Django 4.1.3 on 2022-12-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0056_regressionmetrics_resultsregressionmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsregressionmodel',
            old_name='coefficientStandardErrors',
            new_name='coefficientsStandardErrors',
        ),
        migrations.RenameField(
            model_name='resultsregressionmodel',
            old_name='pValues',
            new_name='pvalues',
        ),
        migrations.RenameField(
            model_name='resultsregressionmodel',
            old_name='test_results',
            new_name='test_result',
        ),
        migrations.RenameField(
            model_name='resultsregressionmodel',
            old_name='train_results',
            new_name='train_result',
        ),
        migrations.RenameField(
            model_name='resultsregressionmodel',
            old_name='tValues',
            new_name='tvalues',
        ),
        migrations.AddField(
            model_name='resultsregressionmodel',
            name='intercept',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_type',
            field=models.CharField(blank=True, choices=[('input', 'Input'), ('columnformatchange', 'Column format change'), ('featureengineering', 'Feature engineering'), ('stationarity', 'Stationarity test'), ('manualvariableselection', 'Manual variable selection'), ('classificationmodel', 'Build logistic regression model'), ('regression', 'Build regression model')], default='input', max_length=100, null=True),
        ),
    ]
