# Generated by Django 4.1.3 on 2022-12-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0058_rename_test_result_resultsregressionmodel_test_results_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsregressionmodel',
            old_name='intercept',
            new_name='intercept_a',
        ),
    ]
