# Generated by Django 4.1.3 on 2022-12-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0059_rename_intercept_resultsregressionmodel_intercept_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsregressionmodel',
            old_name='intercept_a',
            new_name='intercept',
        ),
    ]
