# Generated by Django 4.1.3 on 2023-01-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0062_alter_experiment_experiment_type_featureselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureselection',
            old_name='ignored_features',
            new_name='exclude_features',
        ),
        migrations.AlterField(
            model_name='featureselection',
            name='cross_validation',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='featureselection',
            name='max_features',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='featureselection',
            name='min_features',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='featureselection',
            name='short_list_max_features',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
