# Generated by Django 4.1.3 on 2023-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0064_featureselection_scoring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationmetrics',
            old_name='precision',
            new_name='pr_thresholds',
        ),
        migrations.RenameField(
            model_name='classificationmetrics',
            old_name='recall',
            new_name='precision_plot_data',
        ),
        migrations.RenameField(
            model_name='classificationmetrics',
            old_name='thresholds',
            new_name='recall_plot_data',
        ),
        migrations.AddField(
            model_name='classificationmetrics',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetrics',
            name='f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetrics',
            name='fn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetrics',
            name='fp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetrics',
            name='npv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetrics',
            name='specificity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetrics',
            name='tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetrics',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
