# Generated by Django 4.1.3 on 2023-01-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0066_classificationmetrics_precision_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsclassificationmodel',
            old_name='feature_cols',
            new_name='features',
        ),
    ]
