# Generated by Django 4.1.5 on 2023-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0067_rename_feature_cols_resultsclassificationmodel_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsclassificationmodel',
            name='test_nrows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsclassificationmodel',
            name='train_nrows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
