# Generated by Django 4.1.5 on 2023-01-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0068_resultsclassificationmodel_test_nrows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsEr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
    ]
