# Generated by Django 4.1.5 on 2023-01-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0069_userdetailser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsFeatureselection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_features', models.TextField(blank=True, max_length=20000, null=True)),
                ('quasi_constant_features', models.TextField(blank=True, max_length=20000, null=True)),
                ('correlated_features', models.TextField(blank=True, max_length=20000, null=True)),
                ('duplicated_features', models.TextField(blank=True, max_length=20000, null=True)),
                ('shortlisted_features', models.TextField(blank=True, max_length=20000, null=True)),
                ('selected_features', models.TextField(blank=True, max_length=20000, null=True)),
                ('cv_scores', models.TextField(blank=True, max_length=20000, null=True)),
                ('cv_scores1', models.TextField(blank=True, max_length=20000, null=True)),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic_build.featureselection')),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetailsEr',
        ),
    ]
