# Generated by Django 4.1.5 on 2023-01-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0070_resultsfeatureselection_delete_userdetailser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsfeatureselection',
            name='cv_scores1',
        ),
    ]
