# Generated by Django 4.1.5 on 2023-01-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0072_rename_experiment_resultsfeatureselection_featureselection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsfeatureselection',
            name='featureselection',
        ),
        migrations.AlterField(
            model_name='featureselection',
            name='results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic_build.resultsfeatureselection'),
        ),
    ]
