# Generated by Django 4.1.5 on 2023-01-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0074_rename_result_topmodels_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationmodel',
            name='cross_validation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
