# Generated by Django 4.1.5 on 2023-01-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_build', '0077_experiment_testdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodel',
            name='save_train_test_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='test_data_split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_data_split_randomly', to='logistic_build.traindata'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='train_data_split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_data_split_randomly', to='logistic_build.traindata'),
        ),
    ]
